In [60]:
# libraries 


import numpy as np
import pandas as pd
from sklearn.metrics import pairwise_distances
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.metrics.pairwise import linear_kernel
from scipy import spatial
from scipy.stats.stats import pearsonr
from sklearn.metrics import jaccard_score
from numpy import dot
from numpy.linalg import norm


# Cosine

In [2]:
def cosine1 (vet1, vet2):
  result = cosine_similarity(vet1, vet2)
  return result

In [3]:
def cosine2(vet1, vet2):
  result = 1 - spatial.distance.cosine(vet1, vet2)
  return result

In [4]:
def cosine3(vet1, vet2):
  result = dot(vet1, vet2)/(norm(vet1)*norm(vet2))
  return result

# Correlação

In [36]:
def correlation(vet1, vet2):
  return pearsonr(vet1, vet2)


# Jaccard

In [71]:
def jaccard(vet1, vet2):
  return jaccard_score(vet1, vet2, average='samples')

# Item a

In [69]:
#Cosseno
a = np.array([[1, 1, 1, 1]])
b = np.array([[2, 2, 2, 2]])
print(cosine1(a,b))

[[1.]]


In [38]:
#Cosseno
print(cosine2(a,b))

1.0


In [39]:
#Cosseno
x = [1, 1, 1, 1]
y = [2, 2, 2, 2]

print(cosine3(x,y))

1.0


In [40]:
#Distância Euclidiana
c = [[1, 2],[1, 2], [1, 2], [1,2]]
print(euclidean_distances(c,c))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [44]:
#Correlação linear
print(correlation(x,y))

(nan, nan)


/usr/local/lib/python3.7/dist-packages/scipy/stats/stats.py:3508: PearsonRConstantInputWarning: An input array is constant; the correlation coefficent is not defined.
  warnings.warn(PearsonRConstantInputWarning())


# Item b

In [73]:
#Cosseno
a = np.array([[0, 1, 0, 1]])
b = np.array([[1, 0, 1, 0]])
print(cosine1(a,b))

[[0.]]


In [46]:
#Cosseno
print(cosine2(a,b))

0.0


In [47]:
#Cosseno
x = np.array([0, 1, 0, 1])
y = np.array([1, 0, 1, 0])

print(cosine3(x,y))

0.0


In [48]:
#Distância Euclidiana
c = [[0, 1],[1,0], [0,1], [1,0]]
print(euclidean_distances(c,c))

[[0.         1.41421356 0.         1.41421356]
 [1.41421356 0.         1.41421356 0.        ]
 [0.         1.41421356 0.         1.41421356]
 [1.41421356 0.         1.41421356 0.        ]]


In [51]:
#Correlação linear
print(correlation(x,y))

(-1.0, 0.0)


In [74]:
#Jaccard
print(jaccard(a,b))

0.0


# Item c

In [14]:
#Cosseno
a = np.array([[0, -1, 0, 1]])
b = np.array([[1, 0, -1, 0]])
print(cosine1(a,b))

[[0.]]


In [15]:
#Cosseno
print(cosine2(a,b))

0.0


In [52]:
#Cosseno
x = np.array([0, -1, 0, 1])
y = np.array([1, 0, -1, 0])

print(cosine3(x,y))

0.0


In [35]:
#Distância Euclidiana
c = [[0, 1],[-1,0], [0,-1], [1,0]]
print(euclidean_distances(c,c))

[[0.         1.41421356 2.         1.41421356]
 [1.41421356 0.         1.41421356 2.        ]
 [2.         1.41421356 0.         1.41421356]
 [1.41421356 2.         1.41421356 0.        ]]


In [53]:
#Correlação
print(correlation(x,y))

(0.0, 1.0)


# Item d

In [75]:
#Cosseno
a = np.array([[1, 1, 0, 1, 0, 1]])
b = np.array([[1, 1, 1, 0, 0, 1]])
print(cosine1(a,b))

[[0.75]]


In [42]:
#Cosseno
print(cosine2(a,b))

0.75


In [54]:
#Cosseno
x = np.array([1, 1, 0, 1, 0, 1])
y = np.array([1, 1, 1, 0, 0, 1])

print(cosine3(x,y))

0.75


In [55]:
#Correlação linear
print(correlation(x,y))

(0.24999999999999997, 0.6328125)


In [76]:
#Jaccard
print(jaccard(a,b))

0.6


# Item e

In [45]:
#Cosseno
a = np.array([[2, -1, 0, 2, 0, -3]])
b = np.array([[-1, 1, -1, 0, 0, -1]])
print(cosine1(a,b))

[[0.]]


In [46]:
#Cosseno
print(cosine2(a,b))

0.0


In [56]:
#Cosseno
x = np.array([2, -1, 0, 2, 0, -3])
y = np.array([-1, 1, -1, 0, 0, -1])

print(cosine3(x,y))

0.0


In [57]:
#Correlação Linear
print(correlation(x,y))

(1.0916061966652067e-17, 1.0)


In [77]:
#Correlação Linear
data = np.array([[2,-1], [-1, 1], [0, -1], [2,0], [0, 0], [-3, -1]])
df = pd.DataFrame({'x': data[:,0], 'y': data[:,1]})
df['x'].corr(df['y'])

-2.866583523299505e-17